networks:
  dev:
    driver: bridge

services:
  finapp_api:
    image: finapp_api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - ConnectionStrings__DefaultConnection=User ID=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Server=${POSTGRES_SERVER};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - .env
    depends_on:
      - finapp_db
    networks:
      - dev

  finapp_db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - finapp_data:/var/lib/postgresql/data
    networks:
      - dev
      
  finapp_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports: 
      - "3000:3000"
    depends_on:
      - finapp_api
      - finapp_db
        
volumes: 
  finapp_data:
        
